name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    
     env:
        USER_PHONE: ${{ secrets.USER_PHONE }}
        PASSWORD: ${{secrets.PASSWORD}}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Npm install
      run: npm ci

    - name: Npx run
      run: npx cypress run --headless

    - name: Create test summary
      uses: test-summary/action@v2.0
      if: always()
      with:
        paths: reports/*.xml


    - name: Artifacts
      uses: actions/upload-artifact@v2.2.4
      if: failure()
      with:
        name: cypress-screenshots
        path: ./cypress/screenshots
